### ISSUE TITLE
Use -ouse-numeric-keypad by default if supported

### ISSUE THREAD

**Issue by mscherer** [mcepl/gen-oath-safe#2]
Hi,

I have a french keyboard, and it turn out that this break usage out of the box of the yubikey, see https://qa.ubuntu.com/2012/11/24/yubikey-and-french-keyboard-layout-on-ubuntu/

So I found out of the option, but you have to use it when flashing the key, otherwise you erase the key.

What about setting it by default if the layout is french, and the firmware is sufficient new ( ie > 2.3 ).

**Comment by 72Zn** [comment]
I agree with @mcepl that an in-file allow/block list of keymaps would make maintaining the script needlessly difficult. I think it would be best to let the user decide whether to set the option or not, or simply provide both commands for the user to choose from.
If combined with #3, the user can be prompted when the yubikey configuration is written to the key.
