### ISSUE TITLE
File "<string>", line 1, RHEL7

### ISSUE THREAD

**Issue by ryan33020** [mcepl/gen-oath-safe#5]
Red Hat Enterprise Linux Server release 7.3 (Maipo)
gen-oath-safe-0.10.0-1.el7
generating a key gives a warning
  File "<string>", line 1
    import sys; import base64; import binascii; print base64.b32encode(binascii.unhexlify(sys.stdin.read()))
the created key appears valid but causes force closes in freeotp.

surrounding the statement 
import sys; import base64; import binascii; print (base64.b32encode(binascii.unhexlify(sys.stdin.read())))
allows the token to be created without errors but the created token is invalid.

**Comment by mcepl** [comment]
Do you have python3 as /usr/bin/python? How come it happened?
